name: Run Morning AI Agent

on:
  workflow_dispatch: # Allows you to run it manually from the Actions tab
  schedule:
    # Runs at 12:00 UTC every day (which is 7:00 AM CDT)
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip cache purge
          # ADD --no-cache-dir to force a fresh download
          pip install --no-cache-dir --upgrade google-generativeai requests python-dotenv pytz

      # - name: Run Model Check Script
      #  env:
      #    GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          # Add any other secrets your script needs (like GMAIL, CANVAS, etc.)
      #    GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
      #    GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      #    RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      #    CANVAS_API_TOKEN: ${{ secrets.CANVAS_API_TOKEN }}
      #    CANVAS_BASE_URL: ${{ secrets.CANVAS_BASE_URL }}
      #    WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      #  run: python check_models.py

      # ... (all the steps above)

      # - name: Run Model Check Script # Change the name back
        #env:
        #  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        #  # ... all your other secrets
        #  WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        #run: python check_models.py # <-- Change this line back

      - name: Run the AI agent script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          CANVAS_API_TOKEN: ${{ secrets.CANVAS_API_TOKEN }}
          CANVAS_BASE_URL: ${{ secrets.CANVAS_BASE_URL }}
        run: python -u agent.py
